site_name: lonboard
repo_name: developmentseed/lonboard
repo_url: https://github.com/developmentseed/lonboard
site_description: Extremely fast geospatial data visualization in Jupyter Notebooks
site_author: Development Seed
# Note: trailing slash recommended with mike:
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#publishing-a-new-version
site_url: https://developmentseed.org/lonboard/
docs_dir: docs

extra:
  analytics:
    provider: plausible
    domain: developmentseed.org/lonboard
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: good
          note: Thanks for your feedback!

        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: bad
          note: Thanks for your feedback!
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/developmentseed"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/developmentseed"
    - icon: "fontawesome/brands/medium"
      link: "https://medium.com/devseed"
  version:
    provider: mike

nav:
  - "index.md"
  - Examples:
      - examples/index.md
      - examples/internet-speeds.ipynb
      - examples/north-america-roads.ipynb
      - examples/overture-maps.ipynb
      - examples/global-boundaries.ipynb
      - examples/migration.ipynb
      - examples/data-filter-extension.ipynb
      - Integrations:
          - examples/duckdb.ipynb
          - ColorPicker: examples/integrations/color-picker.ipynb
          - Sidecar: examples/integrations/sidecar.ipynb
      - 30 Day Map Challenge:
          - "Day 1: Points": examples/map_challenge/1-points.ipynb
          - "Day 6: Asia": examples/map_challenge/6-asia.ipynb
  - API Reference:
      - api/viz.md
      - api/map.md
      - Layers:
          - api/layers/bitmap-layer.md
          - api/layers/bitmap-tile-layer.md
          - api/layers/heatmap-layer.md
          - api/layers/path-layer.md
          - api/layers/point-cloud-layer.md
          - api/layers/polygon-layer.md
          - api/layers/scatterplot-layer.md
          - api/layers/solid-polygon-layer.md
          - api/layers/base-layer.md
      - Layer Extensions:
          - api/layer-extensions/index.md
          - api/layer-extensions/brushing-extension.md
          - api/layer-extensions/collision-filter-extension.md
          - api/layer-extensions/data-filter-extension.md
          - api/layer-extensions/path-style-extension.md
      - api/basemap.md
      - api/colormap.md
      - api/controls.md
      - api/traits.md
      - Experimental:
          - Layers:
              - api/layers/arc-layer.md
              - api/layers/text-layer.md
  - cli.md
  - Ecosystem:
      - ecosystem/index.md
      - ecosystem/geopandas.md
      - ecosystem/duckdb.md
      - ecosystem/geoarrow.md
      - ecosystem/jupyter-widgets.md
      - ecosystem/panel.md
      - ecosystem/shiny.md

  # - Caveats: caveats.md
  - Performance: performance.md
  - Changelog: CHANGELOG.md
  - Alternatives: alternatives.md
  - "How it works?":
      - how-it-works/index.md
      - how-it-works/internals.md

watch:
  - lonboard
  - docs

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Roboto
    code: Roboto Mono

  # logo: img/geopolars_logo.svg

  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.share

plugins:
  - search
  - social
  - mike:
      alias_type: "copy"
      canonical_version: "latest"
  - mkdocs-jupyter:
      include_source: true
      ignore: ["**/.ipynb_checkpoints/*.ipynb"]
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          paths: [lonboard]
          options:
            show_root_heading: true
            docstring_style: google
            show_source: false
            docstring_section_style: list
            separate_signature: true
            show_signature_annotations: true
            line_length: 80

          import:
            - https://arrow.apache.org/docs/objects.inv
            - https://contextily.readthedocs.io/en/stable/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://fiona.readthedocs.io/en/stable/objects.inv
            - https://geoarrow.github.io/geoarrow-rs/python/latest/objects.inv
            - https://geopandas.org/en/stable/objects.inv
            - https://geopy.readthedocs.io/en/stable/objects.inv
            - https://ipython.readthedocs.io/en/stable/objects.inv
            - https://ipywidgets.readthedocs.io/en/stable/objects.inv
            - https://matplotlib.org/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pandas.pydata.org/pandas-docs/stable/objects.inv
            - https://pola-rs.github.io/polars/py-polars/html/objects.inv
            - https://pyepsg.readthedocs.io/en/stable/objects.inv
            - https://pygeos.readthedocs.io/en/latest/objects.inv
            - https://pyogrio.readthedocs.io/en/stable/objects.inv
            - https://pyproj4.github.io/pyproj/stable/objects.inv
            - https://pysal.org/libpysal/objects.inv
            - https://pysal.org/mapclassify/objects.inv
            - https://python-visualization.github.io/folium/latest/objects.inv
            - https://rasterio.readthedocs.io/en/stable/objects.inv
            - https://residentmario.github.io/geoplot/objects.inv
            - https://rtree.readthedocs.io/en/stable/objects.inv
            - https://scitools.org.uk/cartopy/docs/latest/objects.inv
            - https://shapely.readthedocs.io/en/stable/objects.inv
            - https://traitlets.readthedocs.io/en/stable/objects.inv
            - https://xyzservices.readthedocs.io/en/stable/objects.inv

# https://github.com/developmentseed/titiler/blob/50934c929cca2fa8d3c408d239015f8da429c6a8/docs/mkdocs.yml#L115-L140
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
