site_name: lonboard
repo_name: developmentseed/lonboard
repo_url: https://github.com/developmentseed/lonboard
site_description: Extremely fast geospatial data visualization in Jupyter Notebooks
site_author: Development Seed
site_url: https://developmentseed.org/lonboard
docs_dir: docs

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/developmentseed"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/developmentseed"
    - icon: "fontawesome/brands/medium"
      link: "https://medium.com/devseed"

nav:
  - "index.md"
  - Example Notebooks:
    - examples/internet-speeds.ipynb
    - examples/north-america-roads.ipynb
  - API Reference:
    - api/viz.md
    - Layers:
      - api/layers/scatterplot-layer.md
      - api/layers/path-layer.md
      - api/layers/solid-polygon-layer.md
    - api/colormap.md
    - api/traits.md
  # - Caveats: caveats.md
  - Performance: performance.md
  - Alternatives: alternatives.md
  - "How it works?": how-it-works.md

watch:
  - lonboard
  - docs

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  # logo: img/geopolars_logo.svg

  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.share

plugins:
  - search
  - social
  - mkdocs-jupyter:
      include_source: True
      ignore: ["**/.ipynb_checkpoints/*.ipynb"]
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          paths: [ lonboard ]
          options:
            show_root_heading: true
            docstring_style: google
            show_source: false
            docstring_section_style: list
            separate_signature: true
            show_signature_annotations: true
            line_length: 80

          import:
            - https://arrow.apache.org/docs/objects.inv
            - https://contextily.readthedocs.io/en/stable/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://fiona.readthedocs.io/en/stable/objects.inv
            - https://geopandas.org/en/stable/objects.inv
            - https://geopy.readthedocs.io/en/stable/objects.inv
            - https://matplotlib.org/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pandas.pydata.org/pandas-docs/stable/objects.inv
            - https://pola-rs.github.io/polars/py-polars/html/objects.inv
            - https://pyepsg.readthedocs.io/en/stable/objects.inv
            - https://pygeos.readthedocs.io/en/latest/objects.inv
            - https://pyogrio.readthedocs.io/en/stable/objects.inv
            - https://pyproj4.github.io/pyproj/stable/objects.inv
            - https://pysal.org/libpysal/objects.inv
            - https://pysal.org/mapclassify/objects.inv
            - https://python-visualization.github.io/folium/latest/objects.inv
            - https://rasterio.readthedocs.io/en/stable/objects.inv
            - https://residentmario.github.io/geoplot/objects.inv
            - https://rtree.readthedocs.io/en/stable/objects.inv
            - https://scitools.org.uk/cartopy/docs/latest/objects.inv
            - https://shapely.readthedocs.io/en/stable/objects.inv
            - https://traitlets.readthedocs.io/en/stable/objects.inv
            - https://xyzservices.readthedocs.io/en/stable/objects.inv


# https://github.com/developmentseed/titiler/blob/50934c929cca2fa8d3c408d239015f8da429c6a8/docs/mkdocs.yml#L115-L140
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
