name: Binder
on:
  push:
    branches:
      - main

jobs:
  # https://github.com/jupyterhub/repo2docker-action#cache-builds-on-mybinderorg
  Create-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    steps:
      - name: cache binder build on mybinder.org
        uses: jupyterhub/repo2docker-action@73f40a661223935d94921712083a929474b78a4f
        with:
          NO_PUSH: true
          MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.
