name: Binder
on:
  push:
    branches:
      - main

jobs:
  # https://github.com/jupyterhub/repo2docker-action#cache-builds-on-mybinderorg
  Create-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    steps:
      - name: cache binder build on mybinder.org
        uses: jupyterhub/repo2docker-action@774bbb1471e3827c67b0a2730ef3a7a217046d5c
        with:
          NO_PUSH: true
          MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.
