name: Binder
on:
  push:
    branches:
      - main

jobs:
  # https://github.com/jupyterhub/repo2docker-action#cache-builds-on-mybinderorg
  Create-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    steps:
      - name: cache binder build on mybinder.org
        uses: jupyterhub/repo2docker-action@00874a0abfebce00bab7eaa3332d3da603c5a2c2
        with:
          NO_PUSH: true
          MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.
