name: Release

# Only run on new tags starting with `v`
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build dist
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.11'

    - name: Build dist
      run: |
        python -m pip install -U build
        python -m build

    - uses: actions/upload-artifact@v2
      with:
        path: ./dist/

  # upload_pypi:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: artifact
  #         path: dist

  #     - uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         user: __token__
  #         password: ${{ secrets.PYPI_API_TOKEN }}
  #         # To test: repository_url: https://test.pypi.org/legacy/
