name: Release

# Only run on new tags starting with `v`
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build dist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11"

      # Note: this should stay synced with the volta-pinned version in
      # package.json
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install JS dependencies
        run: |
          # Note: we use ci for a "clean install", checking the lockfile
          npm ci

      - name: Build JS bundle
        run: |
          npm run build

      - name: Build dist
        run: |
          python -m pip install -U build
          python -m build

      - name: Ensure JS files included
        run: |
          # If no files with path lonboard/static, fail
          unzip -l dist/*.whl | grep "lonboard/static" || exit 1

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/

  upload_pypi:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          # To test: repository_url: https://test.pypi.org/legacy/
