name: JavaScript Build and Lint

on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      # Note: this should stay synced with the volta-pinned version in
      # package.json
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Biome check
        run: pnpm run check
